server:
  port: 9982
  servlet:
    context-path: /tzb
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://47.101.42.177:3306/xhs?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Tzb304213
    hikari:
      max-lifetime: 100000       # 连接最大存活时间（毫秒，建议 <= MySQL 的 wait_timeout）
      idle-timeout: 100000       # 空闲连接超时时间（毫秒）
      connection-timeout: 10000  # 连接超时时间（毫秒）
      validation-timeout: 10000  # 连接校验超时时间（毫秒）
      leak-detection-threshold: 5000  # 检测连接泄漏（毫秒）
  #    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis:
  type-aliases-package: tzb.pojo
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mappers/*.xml



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace

oss:
  endpoint: ${OSS_ENDPOINT}
  accessKeyId: ${OSS_ACCESSKEYID}
  accessKeySecret: ${OSS_ACCESSKEYSECRET}
  bucketName: ${OSS_BUCKETNAME}


